/* eslint-disable react-native/no-inline-styles */
import React from 'react';
import {Text, Pressable, View} from 'react-native';
import ScreenWrapper from '../../hocs/screen_wrapper';
import {useTheme} from 'theme';
import {BackArrow} from 'assets';

const faqs = [
  {
    question: 'What is CAS?',
    answer:
      'CAS statement (Consolidated Account Statement) generated by CAMS reflects mutual fund investments linked to your email ID. You can Import your mutual fund portfolio on FinEzzy with the CAS statement',
  },
  {
    question: 'I have not received CAS statement?',
    answer:
      'Upon your request, CAS generation is initiated with CAMS. We Expect CAMS to send CAS to your email ID within a few hours. IF not received, Please try importing CAS again after 1 working day.',
  },
  {
    question: 'What is the password for my CAS?',
    answer:
      'For CAS import request submitted through FinEzzy, password will be your PAN number in capital letters.',
  },
];

export default function ({navigation}) {
  const theme = useTheme();

  return (
    <ScreenWrapper backgroundColor={theme.colors.background}>
      <View style={{padding: 24}}>
        <View style={{flexDirection: 'row', alignItems: 'center'}}>
          <Pressable
            hitSlop={{top: 30, left: 30, right: 30, bottom: 30}}
            onPress={() => navigation.canGoBack() && navigation.pop()}
            style={{flex: 0.3 / 4}}>
            <BackArrow />
          </Pressable>
          <View
            style={{
              flex: 3.6 / 4,
            }}>
            <Text
              style={{
                textAlign: 'center',
                ...theme.fontSizes.medium,
                fontFamily: theme.fonts.bold,
                color: theme.colors.text,
              }}>
              Portfolio Support
            </Text>
          </View>
        </View>

        <View style={{marginTop: 61}}>
          <Text
            style={{
              ...theme.fontSizes.heading4,
              fontFamily: theme.fonts.bold,
              color: theme.colors.text,
            }}>
            FAQs
          </Text>

          <View style={{marginTop: 24}}>
            {faqs?.map((item, index) => (
              <QA
                key={`faq-${index}`}
                question={item?.question}
                answer={item?.answer}
              />
            ))}
          </View>
        </View>
      </View>
    </ScreenWrapper>
  );
}

const QA = ({question, answer}) => {
  const theme = useTheme();
  const greyTextColorStyle = {
    color: theme.colors.greyscale750,
    ...theme.fontSizes.medium,
    fontFamily: theme.fonts.regular,
  };
  return (
    <View style={{paddingBottom: 16}}>
      <Text
        style={{
          ...greyTextColorStyle,
          color: theme.colors.text,
          fontFamily: theme.fonts.bold,
        }}>
        {`${question}`}
      </Text>
      <Text style={{...greyTextColorStyle}}>{`${answer}`}</Text>
    </View>
  );
};
